/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

/**
 *
 * @author Alherani Junivia
 */
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.koneksi;


public class form_kategori extends javax.swing.JFrame {

    private Statement statement;
    private ResultSet resultset;
    private koneksi koneksi;
    private String id_delete;
    private String idKat;

    public form_kategori() {
        initComponents();
        koneksi = new koneksi();
        Select();
    }
    /**
     * Creates new form form_kategori
     */
    private void Select() {
        try {
            String header[] = {"ID", "Kategori", "Deskripsi"};
            DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
            TabelKategori.setModel(defaultTableModel);


            int baris = TabelKategori.getSelectedRow();

            for (int i = 0; i < baris; i++) {
                defaultTableModel.removeRow(i);
            }

            String sql = "select * from kategori";
            statement = koneksi.connection.createStatement();
            koneksi.connection.createStatement();
            resultset = statement.executeQuery(sql);

            while (resultset.next()) {
                String id = resultset.getString(1);
                String kategori = resultset.getString(2);
                String deskripsi = resultset.getString(3);

                Object isi[] = {id, kategori, deskripsi};
                defaultTableModel.addRow(isi);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void insert() {
        try {
            String sql = "insert into kategori values(null,'" + nmKategori.getText()
                    + "','" + Deskripsi.getText() + "')";
            statement.executeUpdate(sql);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data sudah ada");
        }
    }

    private void delete(){
        try {
            String query = "delete from kategori where idKat='" +idKat+ "'";
            statement.executeUpdate(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void clear() {
        nmKategori.setText("");
        Deskripsi.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Deskripsi = new javax.swing.JTextArea();
        nmKategori = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKategori = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(null);

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(380, 10, 61, 30);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(450, 10, 70, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(30, 10, 55, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 340, 570, 50);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("League Spartan", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM KATEGORI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 240, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 80);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        Deskripsi.setColumns(20);
        Deskripsi.setRows(5);
        jScrollPane2.setViewportView(Deskripsi);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(110, 50, 396, 90);
        jPanel2.add(nmKategori);
        nmKategori.setBounds(110, 10, 176, 30);

        jLabel2.setText("KATEGORI");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 10, 90, 30);

        jLabel3.setText("DESKRIPSI");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 50, 90, 30);

        TabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kategori", "Deskripsi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelKategori);
        if (TabelKategori.getColumnModel().getColumnCount() > 0) {
            TabelKategori.getColumnModel().getColumn(0).setResizable(false);
            TabelKategori.getColumnModel().getColumn(0).setPreferredWidth(5);
            TabelKategori.getColumnModel().getColumn(1).setResizable(false);
            TabelKategori.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(110, 150, 396, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 570, 260);

        setSize(new java.awt.Dimension(582, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (nmKategori.getText().equals("") || Deskripsi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Inputan Anda");
        } else {
            insert();
            Select();
            clear();
    }                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (nmKategori.getText().equals("") || Deskripsi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih data yang akan di Hapus");
        }else{
            delete();
            Select();
            clear();
        }          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TabelKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKategoriMouseClicked
        // TODO add your handling code here:
        idKat = TabelKategori.getValueAt(TabelKategori.getSelectedRow(),0).toString();
        nmKategori.setText(TabelKategori.getValueAt(TabelKategori.getSelectedRow(),1).toString());
        Deskripsi.setText(TabelKategori.getValueAt(TabelKategori.getSelectedRow(),2).toString());
    }//GEN-LAST:event_TabelKategoriMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       new form_barang().show();              
       this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Deskripsi;
    private javax.swing.JTable TabelKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nmKategori;
    // End of variables declaration//GEN-END:variables
}
