/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
//import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.koneksi;

public class form_barang extends javax.swing.JFrame {

    private Statement statement;
    private ResultSet resultset;
    private koneksi koneksi;
    private String id_delete;
    private ResultSet resultSet;
    
    /**
     * Creates new form form_barang
     */
    public form_barang() {
        initComponents();
        koneksi = new koneksi();
        Select();
        PanggilKategoriToComboBox();
    }

    
    private void Select() {
        try {
            String header[] = {"ID BARANG", "KATEGORI", "NAMA_BARANG", "STOK", "HARGA_JUAL"};
            DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
            Tabel_Barang.setModel(defaultTableModel);


            int baris = Tabel_Barang.getSelectedRow();

            for (int i = 0; i < baris; i++) {
                defaultTableModel.removeRow(i);
            }

            String sql = "select * from barang";
            statement = (Statement) koneksi.connection.createStatement();
            resultset = statement.executeQuery(sql);

            while (resultset.next()) {

                String id_barang = resultset.getString(1);
                String ComboBoxK = resultset.getString(2);
                String Nma_Barang = resultset.getString(3);
                String Stok = resultset.getString(4);
                String hrg = resultset.getString(5);
              
                Object isi[] = {id_barang, ComboBoxK, Nma_Barang, Stok, hrg};
                defaultTableModel.addRow(isi);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

     private void insert(){
        try {

            String sql="insert into barang values('"+id_barang.getText()+"','"+kategori.getSelectedItem()+"','" +Nma_Barang.getText()+"','"+Stok.getText()+"','" + harga.getText() + "' )";
            statement.executeUpdate(sql);

        } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void delete() {
        try {
            String query = "delete from barang where id_barang='" + id_barang.getText() + "'";
            statement.executeUpdate(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data telah terpakai");
        }
    }


    private void clear() {
        id_barang.setText("");
        Nma_Barang.setText("");
        Stok.setText("");
        harga.setText("");
    }

    public void update_barang(){

         //panggil method koneksi
        java.sql.Connection conn = new koneksi().connection;


        String sql="update barang set KATEGORI=?, NAMA_BARANG=?, STOK=?, HARGA_JUAL=? where ID_BARANG='"+id_barang.getText()+"'";
        java.sql.PreparedStatement stmt = null;
        try {
            stmt = conn.prepareStatement(sql);
        } catch (Exception ex) {
        }

        try{
            stmt.setString(4,harga.getText());
            stmt.setString(3,Stok.getText());
            stmt.setString(2,Nma_Barang.getText());
            stmt.setString(1,kategori.getSelectedItem().toString());



            stmt.executeUpdate();


        }catch(Exception se){
            JOptionPane.showMessageDialog(null, (se.getMessage()));
        }
    }

    private void PanggilKategoriToComboBox() {
        try {
            kategori.removeAllItems();
            String sql = "select KATEGORI from kategori";
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                kategori.addItem(resultSet.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Barang = new javax.swing.JTable();
        Nma_Barang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        kategori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_barang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Stok = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("League Spartan", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM DAFTAR BARANG ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 400, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 60);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        Tabel_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_BarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Barang);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 170, 500, 102);
        jPanel2.add(Nma_Barang);
        Nma_Barang.setBounds(130, 130, 170, 30);

        jLabel4.setText("NAMA BARANG");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 130, 100, 30);

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(130, 93, 41, 30);

        kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        jPanel2.add(kategori);
        kategori.setBounds(130, 60, 170, 30);

        jLabel3.setText("KATEGORI");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 60, 100, 30);

        jLabel2.setText("ID BARANG");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 100, 30);
        jPanel2.add(id_barang);
        id_barang.setBounds(130, 20, 170, 30);

        jLabel5.setText("STOK");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(360, 20, 70, 30);

        jLabel6.setText("HARGA");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(360, 60, 70, 30);
        jPanel2.add(Stok);
        Stok.setBounds(430, 20, 170, 30);
        jPanel2.add(harga);
        harga.setBounds(430, 60, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 720, 280);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(null);

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(470, 10, 70, 30);

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(550, 10, 60, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(623, 10, 70, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(30, 10, 70, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-1, 340, 720, 50);

        setSize(new java.awt.Dimension(736, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(id_barang.getText().equalsIgnoreCase("") || Nma_Barang.getText().equalsIgnoreCase("")||Stok.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Inputan Anda");
        }else{
            insert();
            Select();
            clear();
    }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Select();
        update_barang();
        Select();
        clear(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if (id_barang.getText().equals("") ||Nma_Barang.getText().equals("")||Stok.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di Hapus");
        } else {

        delete();
        Select();
        clear();
    }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Tabel_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_BarangMouseClicked
        // TODO add your handling code here:
      id_barang.setText(Tabel_Barang.getValueAt(Tabel_Barang.getSelectedRow(),0).toString());
      Stok.setText(Tabel_Barang.getValueAt(Tabel_Barang.getSelectedRow(),3).toString());
       Nma_Barang.setText(Tabel_Barang.getValueAt(Tabel_Barang.getSelectedRow(),2).toString());
       kategori.setSelectedItem(Tabel_Barang.getValueAt(Tabel_Barang.getSelectedRow(),1).toString());
       harga.setText(Tabel_Barang.getValueAt(Tabel_Barang.getSelectedRow(),4).toString());
    }//GEN-LAST:event_Tabel_BarangMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new form_kategori().show();              
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new penjualan().show();              
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nma_Barang;
    private javax.swing.JTextField Stok;
    private javax.swing.JTable Tabel_Barang;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori;
    // End of variables declaration//GEN-END:variables
}
