/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import src.koneksi;
import java.util.*;

/**
 *
 * @author ASUS-PC
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     */
    private Statement statement;
    private ResultSet resultset;
    private koneksi konek;
    private ResultSet resultSet;
    
    public penjualan() {
        initComponents();
        konek = new koneksi();
        select("select nama_barang from barang");
        keranjang.setModel(defaultTableModel);
    }

    private void select(String sql_select) {
       try {
        DefaultListModel model = new DefaultListModel();
        barang.setModel(model);
        model.removeAllElements();

        statement = konek.connection.createStatement();
        resultset = statement.executeQuery(sql_select);
            while (resultset.next()) {
               model.addElement(resultset.getString(1));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        id_bar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        barang = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("League Spartan", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penjualan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 10, 150, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 50);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(null);

        jButton3.setText(" Barang");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(170, 10, 120, 30);

        jButton5.setText("Detail Stok Barang");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(20, 10, 130, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 310, 620, 50);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setLayout(null);

        keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(keranjang);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(350, 50, 260, 150);

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(240, 140, 100, 30);

        jButton1.setText("Tambah -->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(240, 100, 100, 30);

        jButton7.setText("Kosongkan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(240, 60, 100, 30);

        id_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barActionPerformed(evt);
            }
        });
        id_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_barKeyTyped(evt);
            }
        });
        jPanel2.add(id_bar);
        id_bar.setBounds(80, 10, 136, 30);

        jLabel2.setText("ID Barang");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 10, 60, 30);

        barang.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(barang);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 190, 130);

        jLabel3.setText("Jumlah");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 190, 60, 30);
        jPanel2.add(jumlah);
        jumlah.setBounds(80, 190, 140, 30);

        jButton2.setText("Bayar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(410, 210, 152, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Diisi Dulu Jumlahnya");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 224, 130, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 620, 260);

        setSize(new java.awt.Dimension(633, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_barActionPerformed

    String header[]={"Barang","Jumlah","Total"};
    DefaultTableModel defaultTableModel=new DefaultTableModel(null,header);
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        keranjang.setModel(defaultTableModel);
                String brg=barang.getSelectedValue().toString();
                String jml=jumlah.getText();
                String hrg="";
                String sql = "select harga_jual from barang where nama_barang = '" + barang.getSelectedValue().toString() + "'";
        try {
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                hrg = resultSet.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
        hrg = Integer.toString(Integer.parseInt(hrg) * Integer.parseInt(jml));
                Object baris[]={brg,jml,hrg};
                defaultTableModel.addRow(baris);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_barKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_barKeyTyped
        // TODO add your handling code here:
     String sqlSearch="select nama_barang from barang where NAMA_BARANG like '"+id_bar.getText()+"%'";
     select(sqlSearch);
    }//GEN-LAST:event_id_barKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int total=0;
        String nS = new SimpleDateFormat("ddMMyyyy_HHmmss").format(Calendar.getInstance().getTime());
        for(int i = 0; i < keranjang.getModel().getRowCount(); i++){
        total += Integer.parseInt(keranjang.getModel().getValueAt(i, 2).toString());
        }
        JOptionPane.showMessageDialog(null, "Total biaya = " + total);
        for (int i = 0; i < keranjang.getModel().getRowCount(); i++){
            try {
                String sql = "SELECT id_barang FROM barang WHERE nama_barang = '" + keranjang.getModel().getValueAt(i, 0).toString() + "'";
                String idBar;
                statement = konek.connection.createStatement();
                resultset = statement.executeQuery(sql);
                if(resultset.next()){
                    idBar = resultset.getString(1);
                    sql = "INSERT INTO penjualan VALUES (0, ' " + nS + "', '" + variabel.usrname + "', '" + idBar + "', '" + keranjang.getModel().getValueAt(i, 1).toString()
                            + "', '" + keranjang.getModel().getValueAt(i, 2).toString() + "', NOW())";
                    statement = konek.connection.createStatement();
                    statement.execute(sql);
                    
                    sql = "UPDATE `barang` SET `stok`=`stok`-" + keranjang.getModel().getValueAt(i, 1).toString() + " WHERE `id_barang`='" + idBar + "'";
                    statement = konek.connection.createStatement();
                    statement.executeUpdate(sql);
                    
                    JOptionPane.showMessageDialog(null, "Data sudah masuk database");
                }   } catch (SQLException ex) {
                Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new form_barang().show();              
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new form_detail_stok_barang().show();              
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        select("select nama_barang from barang");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        for(int i = defaultTableModel.getRowCount() - 1; i >= 0; i--){
        defaultTableModel.removeRow(i);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList barang;
    private javax.swing.JTextField id_bar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTable keranjang;
    // End of variables declaration//GEN-END:variables
}
